mpc_solver_name: aerial_robot_control::mpc_solver::TiltQdServoThrustDiffSecondOrderMdlMPCSolver
aerial_robot_control_name: aerial_robot_control/differential_mpc_controller/tilt_mt/servo_thrust_diff_second_order_mpc

controller:
  alloc:
    type: 1  # 0: pseudo allocation, 1: heuristic allocation,
    ft_thresh: 1.0  # N

  nmpc:
    T_samp: 0.01  # 100 Hz  TODO: should be adjusted by main_rate
    T_horizon: 2.0  # seconds
    T_step: 0.1  # seconds

    # constraint
    w_min: -6
    w_max: 6  # 1 rad/s ~ 57 deg/s

    v_min: -1
    v_max: 1

    thrust_min: 0  # N
    thrust_max: 23   # N

    thrust_vel_min: -200  # N/s
    thrust_vel_max: 200  # N/s

    a_min: -3.15
    a_max: 3.15  # 180 deg + a little bit

    a_vel_min: -8  # rad/s
    a_vel_max: 8  # rad/s

    Qp_xy: 300
    Qp_z: 400
    Qv_xy: 10
    Qv_z: 10
    Qq_xy: 300
    Qq_z: 600
    Qw_xy: 40
    Qw_z: 40
    Qa: 0.2
    Qt: 0.2
    Qad: 1
    Qtd: 0.0
    Qfu: 0.01 # Generated body force
    Qtau: 0.01 # Generated body torque

    Rtd_c: 0.0001  # Thrust velocity
    Rad_c: 0.01 # Servo angle velocity

    is_attitude_ctrl: false
    is_body_rate_ctrl: false

    is_print_phys_params: false
    is_debug: false
