mpc_solver_name: aerial_robot_control::mpc_solver::TiltQdServoThrustDiffMdlMPCSolver
aerial_robot_control_name: aerial_robot_control/differential_mpc_controller/tilt_mt/servo_thrust_diff_mpc

controller:
  nmpc:
    T_samp: 0.01  # 100 Hz  TODO: should be adjusted by main_rate
    T_horizon: 2.0  # seconds
    T_step: 0.1  # seconds

    # constraint
    w_max: 6  # 1 rad/s ~ 57 deg/s
    w_min: -6

    v_max: 1
    v_min: -1

    thrust_max: 23   # N
    thrust_min: 0  # N

    thrust_vel_max: 1e3  # N/s
    thrust_vel_min: -1e3  # N/s

    a_max: 3.15  # 180 deg + a little bit
    a_min: -3.15

    a_vel_max: 4e1  # rad/s
    a_vel_min: -4e1  # rad/s

    Qp_xy: 300
    Qp_z: 400
    Qv_xy: 10
    Qv_z: 10
    Qq_xy: 300
    Qq_z: 600
    Qw_xy: 5
    Qw_z: 5
    Qa: 1
    Qt: 1
    # Qfu: 0 # Generated body force
    # Qtau: 0 # Generated body torque

    Rtd_c: 0.1  # Thrust velocity
    Rad_c: 10.0 # Servo angle velocity

    is_attitude_ctrl: false
    is_body_rate_ctrl: false

    is_print_phys_params: false
    is_debug: false

