#!/usr/bin/env python3
"""
Differential-Jacobian comparison between PInv(SVD) and PInv(SVD)+Alloc.

The script generates exactly three two-panel figures:

Figure 1: differential-Jacobian rank maps
    left:  PInv(SVD)
    right: PInv(SVD)+Alloc

Figure 2: minimum-singular-value maps
    left:  PInv(SVD)
    right: PInv(SVD)+Alloc

Figure 3:
    left:  Delta sigma_min = sigma_min,heuristic - sigma_min,PInv
    right: horizontal-plane cross section (beta = 0 deg)

The differential allocation Jacobian is

    delta w = J_diff [delta f; delta alpha],

    J_diff = [A_f, A_alpha] in R^(6x8),

where

    A_f     = A_fixed B_f(alpha),
    A_alpha = A_fixed B_alpha(f, alpha).

A dimensionless Jacobian is used for singular-value analysis:

    J_bar = S_w J_diff S_u.

Rank is invariant to nonsingular scaling, whereas the numerical singular
values depend on the selected input/output scales.

Default vehicle:
    generic X-layout tiltable quadrotor
    arm length                 = 0.275 m
    mass                       = 3.039 kg
    yaw moment per thrust      = 0.0165 m
    heuristic thrust threshold = 1.5 N

An actual PhysParamBeetleOmni.yaml can be supplied with --yaml.
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import dataclass
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.colors import BoundaryNorm, ListedColormap, TwoSlopeNorm
import numpy as np
import scienceplots  # noqa: F401  # Registers the "science" matplotlib style.

try:
    import yaml
except ImportError:
    yaml = None


def configure_plot_style() -> None:
    plt.style.use(["science", "grid"])
    plt.rcParams.update(
        {
            "font.size": 14,
            "axes.titlesize": 14,
            "legend.fontsize": 14,
        }
    )


@dataclass(frozen=True)
class VehicleParams:
    positions_b: np.ndarray
    drag_signs: np.ndarray
    yaw_moment_per_thrust_m: float
    mass_kg: float
    gravity_m_s2: float

    @property
    def weight_N(self) -> float:
        return self.mass_kg * self.gravity_m_s2

    @property
    def characteristic_length_m(self) -> float:
        radii = np.linalg.norm(self.positions_b[:, :2], axis=1)
        return float(np.mean(radii))


def generic_params() -> VehicleParams:
    arm_length = 0.275
    coordinate = arm_length / math.sqrt(2.0)

    return VehicleParams(
        positions_b=np.array(
            [
                [coordinate, coordinate, 0.0],
                [-coordinate, coordinate, 0.0],
                [-coordinate, -coordinate, 0.0],
                [coordinate, -coordinate, 0.0],
            ],
            dtype=float,
        ),
        drag_signs=np.array([1.0, -1.0, 1.0, -1.0], dtype=float),
        yaw_moment_per_thrust_m=0.0165,
        mass_kg=3.039,
        gravity_m_s2=9.81,
    )


def load_params_from_yaml(path: Path) -> VehicleParams:
    if yaml is None:
        raise RuntimeError("PyYAML is required when --yaml is used.")

    with path.open("r", encoding="utf-8") as stream:
        data = yaml.safe_load(stream)

    physical = data["physical"]
    return VehicleParams(
        positions_b=np.asarray(
            [physical["p1"], physical["p2"], physical["p3"], physical["p4"]],
            dtype=float,
        ),
        drag_signs=np.asarray(
            [physical["dr1"], physical["dr2"], physical["dr3"], physical["dr4"]],
            dtype=float,
        ),
        yaw_moment_per_thrust_m=float(physical["kq_d_kt"]),
        mass_kg=float(physical["mass"]),
        gravity_m_s2=float(physical["gravity"]),
    )


def build_fixed_allocation_matrix(params: VehicleParams) -> np.ndarray:
    matrix = np.zeros((6, 8), dtype=float)
    gamma = params.yaw_moment_per_thrust_m

    for rotor_index, (position, drag_sign) in enumerate(zip(params.positions_b, params.drag_signs)):
        x_b, y_b, z_b = position
        radius = math.hypot(x_b, y_b)
        if radius <= 0.0:
            raise ValueError(f"Rotor {rotor_index + 1} has zero in-plane arm radius.")

        tangent_column = 2 * rotor_index
        vertical_column = tangent_column + 1

        # Force rows.
        matrix[0, tangent_column] = y_b / radius
        matrix[1, tangent_column] = -x_b / radius
        matrix[2, vertical_column] = 1.0

        # Torque rows generated by the tangential force component.
        matrix[3, tangent_column] = -drag_sign * gamma * y_b / radius + x_b * z_b / radius
        matrix[4, tangent_column] = drag_sign * gamma * x_b / radius + y_b * z_b / radius
        matrix[5, tangent_column] = -radius

        # Torque rows generated by the vertical force component.
        matrix[3, vertical_column] = y_b
        matrix[4, vertical_column] = -x_b
        matrix[5, vertical_column] = -drag_sign * gamma

    return matrix


def svd_pseudoinverse(
    matrix: np.ndarray,
    tolerance: float = 1e-4,
) -> np.ndarray:
    u_matrix, singular_values, vh_matrix = np.linalg.svd(
        matrix,
        full_matrices=True,
    )

    sigma_inverse = np.zeros(
        (matrix.shape[1], matrix.shape[0]),
        dtype=float,
    )
    for index, singular_value in enumerate(singular_values):
        if singular_value > tolerance:
            sigma_inverse[index, index] = 1.0 / singular_value

    return vh_matrix.T @ sigma_inverse @ u_matrix.T


def components_to_commands(
    components: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """Convert [f_t1,f_z1,...] to thrust and servo angle."""
    components = np.asarray(components, dtype=float).reshape(8)
    thrust = np.empty(4, dtype=float)
    alpha = np.empty(4, dtype=float)

    for rotor_index in range(4):
        tangent = float(components[2 * rotor_index])
        vertical = float(components[2 * rotor_index + 1])
        thrust_i = math.hypot(tangent, vertical)

        thrust[rotor_index] = thrust_i
        alpha[rotor_index] = math.atan2(tangent, vertical)

    return thrust, alpha


def choose_heuristic_rotor(
    thrust_N: np.ndarray,
    alpha_rad: np.ndarray,
    thrust_threshold_N: float,
) -> int:
    """
    Select a rotor using only the low-thrust trigger:

        f_i < thrust_threshold_N.

    If more than one rotor satisfies the condition, select the one with the
    largest thrust among the low-thrust candidates.
    """
    del alpha_rad  # Kept only for compatibility with the existing call site.

    candidates = np.where(thrust_N < thrust_threshold_N)[0]

    if candidates.size == 0:
        return -1
    if candidates.size == 1:
        return int(candidates[0])

    return int(candidates[np.argmax(thrust_N[candidates])])


def allocate_pinv(
    target_wrench: np.ndarray,
    fixed_pseudoinverse: np.ndarray,
) -> np.ndarray:
    return fixed_pseudoinverse @ target_wrench


def allocate_pinv_plus_heuristic(
    target_wrench: np.ndarray,
    fixed_matrix: np.ndarray,
    fixed_pseudoinverse: np.ndarray,
    thrust_threshold_N: float,
) -> tuple[np.ndarray, bool, int]:
    """
    Reproduce the PInv(SVD)+Alloc heuristic.

    1. Obtain the PInv force-component solution.
    2. Select a rotor satisfying
           f_i < threshold.
    3. Keep its thrust magnitude and modify its direction.
    4. Remove its wrench contribution.
    5. Allocate the residual wrench with the remaining 6x6 matrix.
    """
    initial_components = fixed_pseudoinverse @ target_wrench
    initial_thrust, initial_alpha = components_to_commands(initial_components)

    selected_rotor = choose_heuristic_rotor(
        initial_thrust,
        initial_alpha,
        thrust_threshold_N,
    )
    if selected_rotor < 0:
        return initial_components, False, -1

    selected_thrust = float(initial_thrust[selected_rotor])
    initial_tangent = float(initial_components[2 * selected_rotor])

    acos_argument = np.clip(
        initial_tangent / thrust_threshold_N,
        -1.0,
        1.0,
    )
    modified_alpha = math.pi / 2.0 - math.acos(float(acos_argument))

    modified_tangent = selected_thrust * math.sin(modified_alpha)
    modified_vertical = selected_thrust * math.cos(modified_alpha)

    selected_components = np.zeros(8, dtype=float)
    selected_components[2 * selected_rotor] = modified_tangent
    selected_components[2 * selected_rotor + 1] = modified_vertical

    residual_wrench = target_wrench - fixed_matrix @ selected_components
    reduced_matrix = np.delete(
        fixed_matrix,
        [2 * selected_rotor, 2 * selected_rotor + 1],
        axis=1,
    )

    try:
        remaining_components = np.linalg.solve(
            reduced_matrix,
            residual_wrench,
        )
    except np.linalg.LinAlgError:
        remaining_components = np.linalg.lstsq(
            reduced_matrix,
            residual_wrench,
            rcond=None,
        )[0]

    final_components = np.insert(
        remaining_components,
        2 * selected_rotor,
        [modified_tangent, modified_vertical],
    )
    return final_components, True, selected_rotor


def thrust_projection_matrix(alpha_rad: np.ndarray) -> np.ndarray:
    matrix = np.zeros((8, 4), dtype=float)

    for rotor_index, alpha_i in enumerate(alpha_rad):
        matrix[2 * rotor_index, rotor_index] = math.sin(alpha_i)
        matrix[2 * rotor_index + 1, rotor_index] = math.cos(alpha_i)

    return matrix


def angle_projection_matrix(
    thrust_N: np.ndarray,
    alpha_rad: np.ndarray,
) -> np.ndarray:
    matrix = np.zeros((8, 4), dtype=float)

    for rotor_index, (thrust_i, alpha_i) in enumerate(zip(thrust_N, alpha_rad)):
        matrix[2 * rotor_index, rotor_index] = thrust_i * math.cos(alpha_i)
        matrix[2 * rotor_index + 1, rotor_index] = -thrust_i * math.sin(alpha_i)

    return matrix


def build_differential_jacobian(
    fixed_matrix: np.ndarray,
    thrust_N: np.ndarray,
    alpha_rad: np.ndarray,
) -> np.ndarray:
    thrust_jacobian = fixed_matrix @ thrust_projection_matrix(alpha_rad)
    angle_jacobian = fixed_matrix @ angle_projection_matrix(thrust_N, alpha_rad)
    return np.hstack((thrust_jacobian, angle_jacobian))


def normalize_differential_jacobian(
    jacobian: np.ndarray,
    params: VehicleParams,
    thrust_increment_scale_N: float,
    angle_increment_scale_rad: float,
) -> np.ndarray:
    output_scaling = np.diag(
        [1.0 / params.weight_N] * 3 + [1.0 / (params.weight_N * params.characteristic_length_m)] * 3
    )
    input_scaling = np.diag([thrust_increment_scale_N] * 4 + [angle_increment_scale_rad] * 4)
    return output_scaling @ jacobian @ input_scaling


def differential_metrics(
    components: np.ndarray,
    fixed_matrix: np.ndarray,
    params: VehicleParams,
    thrust_increment_scale_N: float,
    angle_increment_scale_rad: float,
) -> tuple[int, float, np.ndarray]:
    thrust, alpha = components_to_commands(components)
    jacobian = build_differential_jacobian(
        fixed_matrix,
        thrust,
        alpha,
    )
    normalized_jacobian = normalize_differential_jacobian(
        jacobian,
        params,
        thrust_increment_scale_N,
        angle_increment_scale_rad,
    )

    singular_values = np.linalg.svd(
        normalized_jacobian,
        compute_uv=False,
    )
    tolerance = max(normalized_jacobian.shape) * np.finfo(float).eps * singular_values[0]
    rank = int(np.sum(singular_values > tolerance))
    sigma_min = float(singular_values[-1])

    return rank, sigma_min, singular_values


def direction_from_angles(
    azimuth_rad: float,
    elevation_rad: float,
) -> np.ndarray:
    cos_elevation = math.cos(elevation_rad)
    return np.array(
        [
            cos_elevation * math.cos(azimuth_rad),
            cos_elevation * math.sin(azimuth_rad),
            math.sin(elevation_rad),
        ],
        dtype=float,
    )


def target_wrench_from_direction(
    direction_b: np.ndarray,
    force_magnitude_N: float,
) -> np.ndarray:
    direction_b = np.asarray(direction_b, dtype=float).reshape(3)
    direction_b /= np.linalg.norm(direction_b)

    return np.concatenate((force_magnitude_N * direction_b, np.zeros(3)))


def evaluate_direction(
    direction_b: np.ndarray,
    fixed_matrix: np.ndarray,
    fixed_pseudoinverse: np.ndarray,
    params: VehicleParams,
    thrust_threshold_N: float,
    thrust_increment_scale_N: float,
    angle_increment_scale_rad: float,
) -> dict[str, float | int | bool]:
    target_wrench = target_wrench_from_direction(
        direction_b,
        params.weight_N,
    )

    pinv_components = allocate_pinv(
        target_wrench,
        fixed_pseudoinverse,
    )
    (
        heuristic_components,
        heuristic_activated,
        selected_rotor,
    ) = allocate_pinv_plus_heuristic(
        target_wrench=target_wrench,
        fixed_matrix=fixed_matrix,
        fixed_pseudoinverse=fixed_pseudoinverse,
        thrust_threshold_N=thrust_threshold_N,
    )

    pinv_rank, pinv_sigma_min, _ = differential_metrics(
        pinv_components,
        fixed_matrix,
        params,
        thrust_increment_scale_N,
        angle_increment_scale_rad,
    )
    heuristic_rank, heuristic_sigma_min, _ = differential_metrics(
        heuristic_components,
        fixed_matrix,
        params,
        thrust_increment_scale_N,
        angle_increment_scale_rad,
    )

    return {
        "pinv_rank": pinv_rank,
        "heuristic_rank": heuristic_rank,
        "pinv_sigma_min": pinv_sigma_min,
        "heuristic_sigma_min": heuristic_sigma_min,
        "heuristic_activated": heuristic_activated,
        "selected_rotor": selected_rotor,
    }


def compute_sphere_maps(
    fixed_matrix: np.ndarray,
    fixed_pseudoinverse: np.ndarray,
    params: VehicleParams,
    thrust_threshold_N: float,
    thrust_increment_scale_N: float,
    angle_increment_scale_rad: float,
    azimuth_samples: int,
    elevation_samples: int,
) -> dict[str, np.ndarray]:
    azimuth_deg = np.linspace(
        -180.0,
        180.0,
        azimuth_samples,
    )
    elevation_deg = np.linspace(
        -90.0,
        90.0,
        elevation_samples,
    )
    shape = (elevation_samples, azimuth_samples)

    pinv_rank = np.empty(shape, dtype=int)
    heuristic_rank = np.empty(shape, dtype=int)
    pinv_sigma_min = np.empty(shape, dtype=float)
    heuristic_sigma_min = np.empty(shape, dtype=float)
    heuristic_activated = np.zeros(shape, dtype=bool)

    for row, elevation_i_deg in enumerate(elevation_deg):
        for column, azimuth_i_deg in enumerate(azimuth_deg):
            direction = direction_from_angles(
                math.radians(float(azimuth_i_deg)),
                math.radians(float(elevation_i_deg)),
            )
            result = evaluate_direction(
                direction_b=direction,
                fixed_matrix=fixed_matrix,
                fixed_pseudoinverse=fixed_pseudoinverse,
                params=params,
                thrust_threshold_N=thrust_threshold_N,
                thrust_increment_scale_N=thrust_increment_scale_N,
                angle_increment_scale_rad=angle_increment_scale_rad,
            )

            pinv_rank[row, column] = result["pinv_rank"]
            heuristic_rank[row, column] = result["heuristic_rank"]
            pinv_sigma_min[row, column] = result["pinv_sigma_min"]
            heuristic_sigma_min[row, column] = result["heuristic_sigma_min"]
            heuristic_activated[row, column] = result["heuristic_activated"]

    return {
        "azimuth_deg": azimuth_deg,
        "elevation_deg": elevation_deg,
        "pinv_rank": pinv_rank,
        "heuristic_rank": heuristic_rank,
        "pinv_sigma_min": pinv_sigma_min,
        "heuristic_sigma_min": heuristic_sigma_min,
        "sigma_min_difference": (heuristic_sigma_min - pinv_sigma_min),
        "heuristic_activated": heuristic_activated,
    }


def compute_horizontal_slice(
    fixed_matrix: np.ndarray,
    fixed_pseudoinverse: np.ndarray,
    params: VehicleParams,
    thrust_threshold_N: float,
    thrust_increment_scale_N: float,
    angle_increment_scale_rad: float,
    azimuth_step_deg: float,
) -> dict[str, np.ndarray]:
    azimuth_deg = np.arange(
        -180.0,
        180.0 + 0.5 * azimuth_step_deg,
        azimuth_step_deg,
    )
    pinv_sigma_min = np.empty_like(azimuth_deg)
    heuristic_sigma_min = np.empty_like(azimuth_deg)
    pinv_rank = np.empty(azimuth_deg.size, dtype=int)
    heuristic_rank = np.empty(azimuth_deg.size, dtype=int)
    heuristic_activated = np.zeros(azimuth_deg.size, dtype=bool)

    for index, azimuth_i_deg in enumerate(azimuth_deg):
        direction = direction_from_angles(
            math.radians(float(azimuth_i_deg)),
            0.0,
        )
        result = evaluate_direction(
            direction_b=direction,
            fixed_matrix=fixed_matrix,
            fixed_pseudoinverse=fixed_pseudoinverse,
            params=params,
            thrust_threshold_N=thrust_threshold_N,
            thrust_increment_scale_N=thrust_increment_scale_N,
            angle_increment_scale_rad=angle_increment_scale_rad,
        )

        pinv_sigma_min[index] = result["pinv_sigma_min"]
        heuristic_sigma_min[index] = result["heuristic_sigma_min"]
        pinv_rank[index] = result["pinv_rank"]
        heuristic_rank[index] = result["heuristic_rank"]
        heuristic_activated[index] = result["heuristic_activated"]

    return {
        "azimuth_deg": azimuth_deg,
        "pinv_sigma_min": pinv_sigma_min,
        "heuristic_sigma_min": heuristic_sigma_min,
        "pinv_rank": pinv_rank,
        "heuristic_rank": heuristic_rank,
        "heuristic_activated": heuristic_activated,
    }


def finish_figure(
    figure: plt.Figure,
    output_path: Path,
    show_plots: bool,
) -> None:
    if show_plots:
        return

    figure.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close(figure)


def plot_rank_figure(
    maps: dict[str, np.ndarray],
    output_path: Path,
    show_plots: bool,
) -> None:
    # Match the endpoint colors of the viridis heatmap:
    # rank 5 = minimum-value blue, rank 6 = maximum-value yellow.
    viridis = plt.get_cmap("viridis")
    rank_colormap = ListedColormap([viridis(0.0), viridis(1.0)])
    rank_norm = BoundaryNorm([4.5, 5.5, 6.5], rank_colormap.N)

    figure, axes = plt.subplots(
        1,
        2,
        figsize=(10.0, 4.0),
        sharex=True,
        sharey=True,
    )

    images = []
    for axis, values, title in zip(
        axes,
        [maps["pinv_rank"], maps["heuristic_rank"]],
        ["PInv(SVD)", "PInv(SVD) + heuristic"],
    ):
        image = axis.imshow(
            values,
            origin="lower",
            aspect="auto",
            extent=(-180.0, 180.0, -90.0, 90.0),
            cmap=rank_colormap,
            norm=rank_norm,
            interpolation="nearest",
        )
        images.append(image)

        # Rank-5 configurations are isolated points on this sampling grid.
        # Overlay a visible marker so they remain identifiable after resizing.
        rank_5_rows, rank_5_columns = np.where(values == 5)
        if rank_5_rows.size:
            axis.scatter(
                maps["azimuth_deg"][rank_5_columns],
                maps["elevation_deg"][rank_5_rows],
                marker="o",
                facecolors="none",
                edgecolors="white",
                linewidths=1.2,
                s=30,
            )

        # axis.set_title(title)
        axis.set_xlabel(r"Force azimuth $\phi$ [deg]")

    axes[0].set_ylabel(r"Force elevation $\beta$ [deg]")

    colorbar = figure.colorbar(
        images[0],
        ax=axes,
        ticks=[5, 6],
        fraction=0.026,
        pad=0.02,
        shrink=0.8,
    )
    colorbar.set_label(r"$\operatorname{rank}(\bar{\boldsymbol{J}}_{\mathrm{diff}})$")

    # figure.suptitle("Differential-Jacobian rank")
    figure.subplots_adjust(
        left=0.08,
        right=0.88,
        bottom=0.16,
        top=0.94,
        wspace=0.07,
    )
    finish_figure(figure, output_path, show_plots)


def plot_sigma_min_figure(
    maps: dict[str, np.ndarray],
    output_path: Path,
    show_plots: bool,
) -> None:
    combined = np.concatenate(
        (
            maps["pinv_sigma_min"].ravel(),
            maps["heuristic_sigma_min"].ravel(),
        )
    )
    common_maximum = float(np.percentile(combined, 99.5))

    figure, axes = plt.subplots(
        1,
        2,
        figsize=(10.0, 4.0),
        sharex=True,
        sharey=True,
    )

    images = []
    for axis, values, title in zip(
        axes,
        [
            maps["pinv_sigma_min"],
            maps["heuristic_sigma_min"],
        ],
        ["PInv(SVD)", "PInv(SVD) + heuristic"],
    ):
        image = axis.imshow(
            values,
            origin="lower",
            aspect="auto",
            extent=(-180.0, 180.0, -90.0, 90.0),
            vmin=0.0,
            vmax=common_maximum,
        )
        images.append(image)
        axis.set_title(title)
        axis.set_xlabel(r"Force azimuth $\phi$ [deg]")

    axes[0].set_ylabel(r"Force elevation $\beta$ [deg]")

    # figure.suptitle("Minimum singular value")
    figure.subplots_adjust(
        left=0.08,
        right=0.86,
        bottom=0.16,
        top=0.94,
        wspace=0.07,
    )
    colorbar_axis = figure.add_axes(
        [
            0.88,  # left location
            0.16,  # bottom location
            0.020,  # width
            0.78,  # height
        ]
    )
    colorbar = figure.colorbar(images[0], cax=colorbar_axis)
    colorbar.set_label(r"$\sigma_{\min}(\bar{\boldsymbol{J}}_{\mathrm{diff}})$")

    finish_figure(figure, output_path, show_plots)


def plot_difference_and_horizontal_figure(
    maps: dict[str, np.ndarray],
    horizontal: dict[str, np.ndarray],
    output_path: Path,
    show_plots: bool,
) -> None:
    difference = maps["sigma_min_difference"]
    maximum_absolute_difference = float(np.max(np.abs(difference)))
    if maximum_absolute_difference <= 0.0:
        maximum_absolute_difference = 1.0

    difference_norm = TwoSlopeNorm(
        vmin=-maximum_absolute_difference,
        vcenter=0.0,
        vmax=maximum_absolute_difference,
    )

    figure, axes = plt.subplots(
        1,
        2,
        figsize=(10.5, 4.0),
    )

    image = axes[0].imshow(
        difference,
        origin="lower",
        aspect="auto",
        extent=(-180.0, 180.0, -90.0, 90.0),
        norm=difference_norm,
    )
    axes[0].set_title(r"$\Delta\sigma_{\min}" r"=\sigma_{\min,\mathrm{heuristic}}" r"-\sigma_{\min,\mathrm{PInv}}$")
    axes[0].set_xlabel(r"Force azimuth $\phi$ [deg]")
    axes[0].set_ylabel(r"Force elevation $\beta$ [deg]")

    axes[1].plot(horizontal["azimuth_deg"], horizontal["pinv_sigma_min"], label="PInv(SVD)", color="C0")
    axes[1].plot(
        horizontal["azimuth_deg"], horizontal["heuristic_sigma_min"], label="PInv(SVD) + heuristic", color="C2"
    )
    axes[1].set_title(r"Horizontal-plane section: $\beta=0^\circ$")
    axes[1].set_xlabel(r"Force azimuth $\phi$ [deg]")
    axes[1].set_ylabel(r"$\sigma_{\min}(\bar{\boldsymbol{J}}_{\mathrm{diff}})$")
    axes[1].set_xlim(-180.0, 180.0)
    axes[1].grid(True)
    axes[1].legend(loc="upper right", framealpha=0.8)

    figure.subplots_adjust(
        left=0.08,
        right=0.95,
        bottom=0.16,
        top=0.94,
        wspace=0.6,
    )

    # Get the final position of the left subplot.
    left_axis_position = axes[0].get_position()

    # Adjust this value to change the colorbar height.
    colorbar_height_ratio = 1.0
    colorbar_height = left_axis_position.height * colorbar_height_ratio

    # Vertically center the colorbar relative to the left subplot.
    colorbar_bottom = left_axis_position.y0 + (left_axis_position.height - colorbar_height) / 2.0

    colorbar_axis = figure.add_axes(
        [
            left_axis_position.x1 + 0.012,  # distance from the left plot
            colorbar_bottom,
            0.012,  # colorbar width
            colorbar_height,
        ]
    )

    difference_colorbar = figure.colorbar(
        image,
        cax=colorbar_axis,
    )
    difference_colorbar.set_label(
        r"$\Delta\sigma_{\min}$",
        labelpad=3,
    )

    finish_figure(figure, output_path, show_plots)


def main() -> None:
    configure_plot_style()

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--yaml",
        type=Path,
        default=None,
        help="Optional PhysParamBeetleOmni.yaml path.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("differential_jacobian_final_figures"),
    )
    parser.add_argument(
        "--thrust-threshold",
        type=float,
        default=1.5,
        help="Heuristic low-thrust threshold [N].",
    )
    parser.add_argument(
        "--thrust-increment-scale",
        type=float,
        default=None,
        help="Default: vehicle weight / 4 [N].",
    )
    parser.add_argument(
        "--angle-increment-scale-deg",
        type=float,
        default=57.29577951308232,
        help="Default: 1 rad.",
    )
    parser.add_argument(
        "--azimuth-samples",
        type=int,
        default=361,
    )
    parser.add_argument(
        "--elevation-samples",
        type=int,
        default=181,
    )
    parser.add_argument(
        "--horizontal-step-deg",
        type=float,
        default=0.05,
    )
    parser.add_argument(
        "--show-plots",
        action="store_true",
        help="Display plots interactively instead of saving PNG files.",
    )
    args = parser.parse_args()

    params = load_params_from_yaml(args.yaml) if args.yaml is not None else generic_params()
    fixed_matrix = build_fixed_allocation_matrix(params)
    fixed_pseudoinverse = svd_pseudoinverse(fixed_matrix)

    thrust_increment_scale_N = (
        args.thrust_increment_scale if args.thrust_increment_scale is not None else params.weight_N / 4.0
    )
    angle_increment_scale_rad = math.radians(args.angle_increment_scale_deg)

    args.output_dir.mkdir(parents=True, exist_ok=True)

    maps = compute_sphere_maps(
        fixed_matrix=fixed_matrix,
        fixed_pseudoinverse=fixed_pseudoinverse,
        params=params,
        thrust_threshold_N=args.thrust_threshold,
        thrust_increment_scale_N=thrust_increment_scale_N,
        angle_increment_scale_rad=angle_increment_scale_rad,
        azimuth_samples=args.azimuth_samples,
        elevation_samples=args.elevation_samples,
    )
    horizontal = compute_horizontal_slice(
        fixed_matrix=fixed_matrix,
        fixed_pseudoinverse=fixed_pseudoinverse,
        params=params,
        thrust_threshold_N=args.thrust_threshold,
        thrust_increment_scale_N=thrust_increment_scale_N,
        angle_increment_scale_rad=angle_increment_scale_rad,
        azimuth_step_deg=args.horizontal_step_deg,
    )

    # plot_rank_figure(
    #     maps,
    #     args.output_dir / "figure_1_rank_maps.png",
    #     args.show_plots,
    # )
    plot_sigma_min_figure(
        maps,
        args.output_dir / "figure_2_sigma_min_maps.png",
        args.show_plots,
    )
    plot_difference_and_horizontal_figure(
        maps,
        horizontal,
        args.output_dir / "figure_3_sigma_difference_and_horizontal_section.png",
        args.show_plots,
    )

    np.savez_compressed(
        args.output_dir / "differential_jacobian_figure_data.npz",
        **maps,
        **{f"horizontal_{key}": value for key, value in horizontal.items()},
        fixed_matrix=fixed_matrix,
        positions_b=params.positions_b,
        drag_signs=params.drag_signs,
        mass_kg=params.mass_kg,
        gravity_m_s2=params.gravity_m_s2,
        yaw_moment_per_thrust_m=(params.yaw_moment_per_thrust_m),
        thrust_threshold_N=args.thrust_threshold,
        thrust_increment_scale_N=(thrust_increment_scale_N),
        angle_increment_scale_rad=(angle_increment_scale_rad),
    )

    rank_summary = {
        "pinv_rank_values": np.unique(maps["pinv_rank"]).astype(int).tolist(),
        "heuristic_rank_values": np.unique(maps["heuristic_rank"]).astype(int).tolist(),
        "pinv_rank_5_samples": int(np.sum(maps["pinv_rank"] == 5)),
        "heuristic_rank_5_samples": int(np.sum(maps["heuristic_rank"] == 5)),
        "heuristic_activation_fraction_percent": float(100.0 * np.mean(maps["heuristic_activated"])),
        "minimum_pinv_sigma_min": float(np.min(maps["pinv_sigma_min"])),
        "minimum_heuristic_sigma_min": float(np.min(maps["heuristic_sigma_min"])),
        "maximum_sigma_min_improvement": float(np.max(maps["sigma_min_difference"])),
        "minimum_sigma_min_change": float(np.min(maps["sigma_min_difference"])),
    }

    with (args.output_dir / "figure_summary.json").open("w", encoding="utf-8") as stream:
        json.dump(rank_summary, stream, indent=2)

    print("Fixed 6x8 allocation matrix:")
    np.set_printoptions(precision=6, suppress=True)
    print(fixed_matrix)
    print("\nSummary:")
    for key, value in rank_summary.items():
        print(f"  {key}: {value}")
    print(f"\nData saved to: {args.output_dir.resolve()}")

    if args.show_plots:
        print("Displaying plots interactively; PNG files were not saved.")
        plt.show()
    else:
        print("PNG figures saved to the output directory.")


if __name__ == "__main__":
    main()
