#!/usr/bin/env python3
"""
Compute the pitch angle required for a conventional quadrotor with a 2-DoF arm
when applying a horizontal contact force to a wall.

Model assumptions
-----------------
1. The quadrotor is a conventional fixed-rotor quadrotor. The total rotor force
   is along the body z-axis.
2. The vehicle is in quasi-static equilibrium.
3. The total mass includes the vehicle and the arm.
4. The wall contact force is horizontal. The input f is the force magnitude in N.
5. The first arm link is vertical downward and has length L1. The second link is
   horizontal and has length L2. For the pitch moment generated by a horizontal
   force along the second-link direction, only the vertical offset L1 matters.
6. Arm mass and joint torque limits are ignored in this simple calculation.

Force equilibrium gives
    theta = atan2(f, m*g)
    T_req = sqrt((m*g)^2 + f^2)
where theta is the body pitch tilt magnitude from level flight.

A simple pitch-moment feasibility check is also included. The contact force
creates a pitch moment approximately
    tau_contact_y = L1 * f.
For an X-type quadrotor whose rotor-to-CoG radius is L_rotor, the projected
front/rear pitch-moment arm is L_rotor / sqrt(2). The maximum pitch moment at a
fixed total thrust T_req is limited by rotor saturation.
"""

from __future__ import annotations

import argparse
import math
from dataclasses import dataclass
from typing import Iterable


@dataclass(frozen=True)
class QuadrotorArmParams:
    """Physical parameters for the simplified static model."""

    rotor_arm_length_m: float = 0.275  # distance from each rotor to vehicle center
    arm_link1_length_m: float = 0.275  # vertical downward link length
    arm_link2_length_m: float = 0.275  # horizontal link length; not used for pitch force moment
    mass_kg: float = 3.039
    gravity_m_s2: float = 9.81
    max_thrust_per_rotor_N: float = 23.0

    @property
    def weight_N(self) -> float:
        return self.mass_kg * self.gravity_m_s2

    @property
    def max_total_thrust_N(self) -> float:
        return 4.0 * self.max_thrust_per_rotor_N

    @property
    def pitch_moment_arm_m(self) -> float:
        """Projected pitch moment arm for an X-type quadrotor."""

        return self.rotor_arm_length_m / math.sqrt(2.0)


@dataclass(frozen=True)
class PitchResult:
    """Result for one requested contact force."""

    contact_force_N: float
    pitch_angle_rad: float
    pitch_angle_deg: float
    required_total_thrust_N: float
    thrust_feasible: bool
    contact_pitch_moment_Nm: float
    max_available_pitch_moment_Nm: float
    moment_feasible: bool
    front_rotor_thrust_N: float | None
    rear_rotor_thrust_N: float | None

    @property
    def feasible(self) -> bool:
        return self.thrust_feasible and self.moment_feasible


def max_pitch_moment_at_total_thrust(total_thrust_N: float, params: QuadrotorArmParams) -> float:
    """Return the maximum absolute pitch moment available at fixed total thrust.

    The model assumes an X-type layout with two front rotors and two rear rotors.
    Let T_f and T_r be the total thrusts of the front and rear rotor pairs. Then
        T_f + T_r = T,
        tau_y = (L_rotor / sqrt(2)) * (T_r - T_f),
    with 0 <= T_f, T_r <= 2*T_max.
    """

    if total_thrust_N < 0.0 or total_thrust_N > params.max_total_thrust_N:
        return 0.0

    pair_limit = 2.0 * params.max_thrust_per_rotor_N
    max_pair_difference = min(total_thrust_N, 2.0 * pair_limit - total_thrust_N)
    return params.pitch_moment_arm_m * max(0.0, max_pair_difference)


def compute_pitch_for_contact_force(
    f_N: float,
    params: QuadrotorArmParams = QuadrotorArmParams(),
    contact_moment_sign: float = 1.0,
) -> PitchResult:
    """Compute pitch angle and a simple feasibility check for contact force f_N.

    Parameters
    ----------
    f_N:
        Horizontal wall-contact force magnitude in N. A signed value is allowed;
        the pitch angle is signed according to f_N.
    params:
        Physical parameters.
    contact_moment_sign:
        Sign convention for the pitch moment produced by the contact force.
        It does not affect the pitch-angle magnitude or feasibility.
    """

    weight = params.weight_N

    # Static force equilibrium. Positive f_N gives a positive pitch angle in this
    # script. Depending on the coordinate convention, the physical pitch sign may
    # be the opposite; the magnitude is unchanged.
    theta_rad = math.atan2(f_N, weight)
    theta_deg = math.degrees(theta_rad)
    total_thrust = math.hypot(weight, f_N)
    thrust_feasible = total_thrust <= params.max_total_thrust_N + 1e-12

    # Static pitch-moment equilibrium caused by the vertical offset of the end-effector.
    tau_contact_y = contact_moment_sign * params.arm_link1_length_m * f_N
    tau_needed_abs = abs(tau_contact_y)
    tau_max_abs = max_pitch_moment_at_total_thrust(total_thrust, params)
    moment_feasible = tau_needed_abs <= tau_max_abs + 1e-12

    # One possible front/rear rotor-pair distribution to balance the contact moment.
    # Required propeller pitch moment is tau_prop_y = -tau_contact_y.
    # tau_prop_y = (L_rotor / sqrt(2)) * (T_rear_pair - T_front_pair).
    if thrust_feasible:
        tau_prop_y = -tau_contact_y
        rear_pair_total = 0.5 * (total_thrust + tau_prop_y / params.pitch_moment_arm_m)
        front_pair_total = 0.5 * (total_thrust - tau_prop_y / params.pitch_moment_arm_m)
        rear_rotor = rear_pair_total / 2.0
        front_rotor = front_pair_total / 2.0

        rotor_distribution_feasible = (
            -1e-12 <= rear_rotor <= params.max_thrust_per_rotor_N + 1e-12
            and -1e-12 <= front_rotor <= params.max_thrust_per_rotor_N + 1e-12
        )
        moment_feasible = moment_feasible and rotor_distribution_feasible

        if not rotor_distribution_feasible:
            rear_rotor = None
            front_rotor = None
    else:
        rear_rotor = None
        front_rotor = None

    return PitchResult(
        contact_force_N=f_N,
        pitch_angle_rad=theta_rad,
        pitch_angle_deg=theta_deg,
        required_total_thrust_N=total_thrust,
        thrust_feasible=thrust_feasible,
        contact_pitch_moment_Nm=tau_contact_y,
        max_available_pitch_moment_Nm=tau_max_abs,
        moment_feasible=moment_feasible,
        front_rotor_thrust_N=front_rotor,
        rear_rotor_thrust_N=rear_rotor,
    )


def print_results(results: Iterable[PitchResult]) -> None:
    header = (
        "f [N]",
        "pitch [deg]",
        "T_req [N]",
        "tau_contact_y [Nm]",
        "tau_y_max [Nm]",
        "front rotor [N]",
        "rear rotor [N]",
        "feasible",
    )
    print(
        f"{header[0]:>10s}  {header[1]:>12s}  {header[2]:>10s}  "
        f"{header[3]:>18s}  {header[4]:>14s}  {header[5]:>15s}  "
        f"{header[6]:>14s}  {header[7]:>8s}"
    )
    print("-" * 120)

    for r in results:
        front = "--" if r.front_rotor_thrust_N is None else f"{r.front_rotor_thrust_N:.3f}"
        rear = "--" if r.rear_rotor_thrust_N is None else f"{r.rear_rotor_thrust_N:.3f}"
        print(
            f"{r.contact_force_N:10.3f}  {r.pitch_angle_deg:12.3f}  "
            f"{r.required_total_thrust_N:10.3f}  {r.contact_pitch_moment_Nm:18.3f}  "
            f"{r.max_available_pitch_moment_Nm:14.3f}  {front:>15s}  "
            f"{rear:>14s}  {str(r.feasible):>8s}"
        )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Compute pitch tilt angle for a conventional quadrotor pushing a wall."
    )
    parser.add_argument(
        "forces",
        nargs="*",
        type=float,
        help="Contact force values in N. Example: 5 10 20. If omitted, a default sweep is used.",
    )
    parser.add_argument("--mass", type=float, default=3.039, help="Total mass in kg.")
    parser.add_argument("--g", type=float, default=9.81, help="Gravity in m/s^2.")
    parser.add_argument("--l", type=float, default=0.275, help="Rotor arm length and arm link length in m.")
    parser.add_argument("--fmax", type=float, default=23.0, help="Maximum thrust per rotor in N.")
    args = parser.parse_args()

    params = QuadrotorArmParams(
        rotor_arm_length_m=args.l,
        arm_link1_length_m=args.l,
        arm_link2_length_m=args.l,
        mass_kg=args.mass,
        gravity_m_s2=args.g,
        max_thrust_per_rotor_N=args.fmax,
    )

    forces = args.forces if args.forces else [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60]
    results = [compute_pitch_for_contact_force(f, params) for f in forces]

    print("Parameters:")
    print(f"  mass = {params.mass_kg:.3f} kg")
    print(f"  g = {params.gravity_m_s2:.3f} m/s^2")
    print(f"  rotor radius/link length = {params.rotor_arm_length_m:.3f} m")
    print(f"  X-layout pitch moment arm = {params.pitch_moment_arm_m:.3f} m")
    print(f"  max thrust per rotor = {params.max_thrust_per_rotor_N:.3f} N")
    print(f"  weight = {params.weight_N:.3f} N")
    print(f"  max total thrust = {params.max_total_thrust_N:.3f} N")
    print()

    print_results(results)


if __name__ == "__main__":
    main()
