beetle1:
  admittance:
    force_thresh: 0.5
    torque_thresh: 0.1

    Mp: [3.0, 3.0, 3.0]
    Dp: [10.0, 10.0, 10.0]
    Kp: [20.0, 20.0, 20.0]

    Mq: [0.5, 0.5, 0.5]
    Dq: [5.0, 5.0, 5.0]
    Kq: [5.0, 5.0, 5.0]
